# Generated by Django 5.2.8 on 2025-11-27 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=100)),
                ('jenis_dagangan', models.CharField(max_length=100)),
                ('jam_operasional', models.CharField(max_length=100)),
                ('status_aktif', models.BooleanField(default=False)),
                ('alamat_domisili', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pkl_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LokasiPKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='AKTIF', max_length=50)),
                ('pkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lokasi', to='pkl.pkl')),
            ],
        ),
    ]
