# Generated by Django 5.2.8 on 2025-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkl',
            name='catatan_verifikasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pkl',
            name='status_verifikasi',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak')], default='PENDING', max_length=20),
        ),
    ]
