# Generated by Django 5.2.8 on 2025-11-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0002_pkl_catatan_verifikasi_pkl_status_verifikasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasipkl',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lokasipkl',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
