# Generated by Django 5.2.8 on 2025-12-01 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0003_alter_lokasipkl_latitude_alter_lokasipkl_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_pembeli', to=settings.AUTH_USER_MODEL)),
                ('pkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='pkl.pkl')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('pembeli', 'pkl')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pkl.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
