# Generated by Django 5.2.8 on 2025-12-01 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0004_chat_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_pesanan', models.TextField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak'), ('SELESAI', 'Selesai')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to=settings.AUTH_USER_MODEL)),
                ('pkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='pkl.pkl')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
