# Generated by Django 5.2.8 on 2025-12-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0005_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkl',
            name='nama_rekening',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pkl',
            name='qris_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pkl',
            name='qris_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='bukti_dp_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='dp_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preorder',
            name='dp_status',
            field=models.CharField(choices=[('BELUM_BAYAR', 'Belum Bayar'), ('MENUNGGU_KONFIRMASI', 'Menunggu Konfirmasi'), ('TERKONFIRMASI', 'Terkonfirmasi')], default='BELUM_BAYAR', max_length=30),
        ),
    ]
