# Generated by Django 5.2.8 on 2025-12-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0007_buyerlocation_notification_favoritepkl'),
    ]

    operations = [
        migrations.CreateModel(
            name='PKLDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('live_views', models.PositiveIntegerField(default=0)),
                ('search_hits', models.PositiveIntegerField(default=0)),
                ('auto_updates', models.PositiveIntegerField(default=0)),
                ('pkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='pkl.pkl')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('pkl', 'date')},
            },
        ),
    ]
