# Generated by Django on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0007_buyerlocation_notification_favoritepkl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkl',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
