# Generated by Django 5.2.7 on 2025-12-03 13:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0008_pkldailystats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PKLRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkl_ratings', to=settings.AUTH_USER_MODEL)),
                ('pkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pkl.pkl')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('buyer', 'pkl')},
            },
        ),
    ]
