# Generated by Django 5.2.7 on 2025-12-03 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0009_pklrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PKLProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pkl_products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pkl.pkl')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
