# Generated by Django on 2025-12-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0011_pkl_tentang'),
        ('pkl', '0008_pkl_profile_image_url'),
    ]

    operations = []
