# Generated by Django 5.2.8 on 2026-03-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0012_pkl_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pkl.preorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pkl.pklproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
