# Generated by Django 5.2.8 on 2026-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkl', '0013_preorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
